### ISSUE TITLE
nginx未配置

### ISSUE THREAD

**Issue by passerby660** [ermaozi/trojan-go-panel#1]
配置好后通过网址访问,显示的是nginx的默认欢迎界面,根据install里面的代码去conf里面,没有找到nginx相关的配置.

**Comment by ermaozi** [comment]
非常抱歉，因为近期较忙，加之本项目没什么动静，导致我忘记继续开发了。
目前这个项目还是半成品，伪装网站等功能未实装。
如果有需要的话可以在/etc/nginx/目录下找到相关配置文件。
后期我会尽快完善功能。

**Comment by ckbkdj** [comment]
大佬一忙你就网了

**Comment by ckbkdj** [comment]
大佬一忙你就忘记更新了

**Comment by ermaozi** [comment]
> 大佬一忙你就忘记更新了

近期重新启动开发了, 后续这个工具会具备多用户多节点的管理功能

**Comment by ckbkdj** [comment]
大佬牛逼!
