### ISSUE TITLE
请问一下安装过程中报服务启动失败 是什么情况导致的

### ISSUE THREAD

**Issue by zxc2616043** [ermaozi/trojan-go-panel#5]
![企业微信截图_16272927318708](https://user-images.githubusercontent.com/81410386/126969137-6fbe215f-4346-483d-a803-a8c75e31ba3c.png)

**Comment by ermaozi** [comment]
访问一下你的域名试试看能不能正常访问，我刚看了一下安装脚本，这种情况应该是脚本bug导致的误报

**Comment by zxc2616043** [comment]
能访问主界面 但是注册没有反应

> 访问一下你的域名试试看能不能正常访问，我刚看了一下安装脚本，这种情况应该是脚本bug导致的误报
